# 第二章

In [1]:
import numpy as np

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

In [10]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [11]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [12]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
 data = np.array([1, 2, 3], dtype=np.float)
 data

array([1., 2., 3.])

In [15]:
data.dtype

dtype('float64')

In [16]:
data = np.array(data, dtype=np.int)

In [17]:
data.dtype

dtype('int32')

In [18]:
 data

array([1, 2, 3])

In [19]:
data = np.array([1, 2, 3], dtype=np.float)
data

array([1., 2., 3.])

In [20]:
data.astype(np.int)

array([1, 2, 3])

In [21]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [22]:
(d1 + d2).dtype

dtype('complex128')

In [23]:
np.sqrt(np.array([-1, 0, 1]))

<ipython-input-23-18cc2be45d00>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [24]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

In [25]:
data = np.array([1, 2, 3], dtype=complex)
data

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
 data.real

array([1., 2., 3.])

In [27]:
data.imag

array([0., 0., 0.])

In [28]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [29]:
 data.ndim

1

In [30]:
data.shape

(3,)

In [31]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [32]:
data.ndim

1

In [33]:
data.shape

(3,)

In [34]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
data = np.ones(4)

In [37]:
data.dtype

dtype('float64')

In [38]:
 data = np.ones(4, dtype=np.int64)
data.dtype

dtype('int64')

In [39]:
x1 = 5.4 * np.ones(10)
x2 = np.full(10, 5.4)

In [40]:
x1 = np.empty(5)
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

In [41]:
x2 = np.full(5, 3.0)
x2

array([3., 3., 3., 3., 3.])

In [42]:
 np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [45]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X, Y = np.meshgrid(x, y)
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [46]:
 Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [47]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

In [48]:
np.empty(3, dtype=np.float)

array([0., 0., 0.])

In [49]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [51]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [53]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
 a[0] # the first element

0

In [55]:
a[-1] # the last element

10

In [56]:
 a[4] # the fifth element, at index 4

4

In [57]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [59]:
a[:5]

array([0, 1, 2, 3, 4])

In [60]:
 a[-5:]

array([ 6,  7,  8,  9, 10])

In [61]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

In [62]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [63]:
A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [64]:
A[1, :] # the second row

array([10, 11, 12, 13, 14, 15])

In [65]:
A[:3, :3] # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [66]:
A[3:, :3] # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [67]:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [68]:
A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

In [69]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [70]:
B[:, :] = 0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [71]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [75]:
C[:, :] = 1 # this does not affect B since C is a copy of the view B[1:3, 1:3]
C

array([[1, 1],
       [1, 1]])

In [76]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
 A = np.linspace(0, 1, 11)

In [78]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [79]:
 A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

In [80]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [81]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [82]:
A = np.arange(10)

In [83]:
indices = [2, 4, 6]

In [84]:
 B = A[indices]

In [85]:
B[0] = -1 # this does not affect A
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
A[indices] = -1 # this alters A
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [87]:
A = np.arange(10)
B = A[A > 5]
B[0] = -1 # this does not affect A
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
A[A > 5] = -1 # this alters A
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [90]:
data = np.array([[1, 2], [3, 4]])
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [91]:
data.reshape(4)

array([1, 2, 3, 4])

In [92]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [93]:
data.flatten()

array([1, 2, 3, 4])

In [94]:
data.flatten().shape

(4,)

In [95]:
data = np.arange(0, 5)
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [96]:
 row = data[np.newaxis, :]
 row

array([[0, 1, 2, 3, 4]])

In [97]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [98]:
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [99]:
 data = np.arange(5)
 data

array([0, 1, 2, 3, 4])

In [100]:
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [101]:
data = data[:, np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [102]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x + y

array([[ 6,  8],
       [10, 12]])

In [103]:
 y - x

array([[4, 4],
       [4, 4]])

In [104]:
 x * y

array([[ 5, 12],
       [21, 32]])

In [105]:
 y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [106]:
x * 2

array([[2, 4],
       [6, 8]])

In [107]:
2 ** x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [108]:
y / 2

array([[2.5, 3. ],
       [3.5, 4. ]])

In [109]:
(y / 2).dtype

dtype('float64')

In [110]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
z = np.array([1, 2, 3, 4])
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [111]:
z = np.array([[2, 4]])
z.shape

(1, 2)

In [112]:
 x / z

array([[0.5, 0.5],
       [1.5, 1. ]])

In [113]:
zz = np.concatenate([z, z], axis=0)
zz

array([[2, 4],
       [2, 4]])

In [114]:
x / zz

array([[0.5, 0.5],
       [1.5, 1. ]])

In [115]:
z = np.array([[2], [4]])
z.shape

(2, 1)

In [116]:
x / z

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [117]:
zz = np.concatenate([z, z], axis=1)
zz

array([[2, 2],
       [4, 4]])

In [118]:
 x / zz

array([[0.5 , 1.  ],
       [0.75, 1.  ]])

In [119]:
 x = x + y
 x += y

In [120]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [121]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)

array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [122]:
 np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [123]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
def heaviside(x):
    return 1 if x > 0 else 0

In [125]:
heaviside(-1)

0

In [126]:
heaviside(1.5)

1

In [127]:
x = np.linspace(-5, 5, 11)
heaviside(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [128]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [129]:
def heaviside(x):
    return 1.0 * (x > 0)

In [130]:
data = np.random.normal(size=(15,15))
np.mean(data)

-0.012826653080682779

In [131]:
data.mean()

-0.012826653080682779

In [132]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [134]:
data.sum(axis=(0, 2)).shape

(10,)

In [135]:
data.sum()

27.093758927546826

In [136]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
data.sum()

45

In [138]:
data.sum(axis=0)

array([12, 15, 18])

In [139]:
 data.sum(axis=1)

array([ 6, 15, 24])

In [140]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b

array([ True,  True, False, False])

In [141]:
np.all(a < b)

False

In [142]:
np.any(a < b)

True

In [150]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
     print("Some elements in a are smaller than their corresponding element in b")
else:
    print("All elements in b are smaller than their corresponding element in a")                

Some elements in a are smaller than their corresponding element in b


In [151]:
x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [152]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [153]:
 x * (x > 0)

array([0, 0, 0, 1, 2])

In [154]:
def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))
    

In [155]:
x = np.linspace(-5, 5, 11)

In [156]:
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [157]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [158]:
def pulse(x, position, height, width): 
    return height * np.logical_and(x >= position, x <= (position +
width))

In [159]:
x = np.linspace(-4, 4, 9)
np.where(x < 0, x**2, x**3)

array([16.,  9.,  4.,  1.,  0.,  1.,  8., 27., 64.])

In [160]:
np.select([x < -1, x < 2, x >= 2],
          [x**2 , x**3 , x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [161]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],
          [x**2, x**3, x**4])

array([ 16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256.])

In [162]:
 np.nonzero(abs(x) > 2)

(array([0, 1, 7, 8], dtype=int64),)

In [163]:
 x[np.nonzero(abs(x) > 2)]

array([-4., -3.,  3.,  4.])

In [164]:
x[abs(x) > 2]

array([-4., -3.,  3.,  4.])

In [165]:
a = np.unique([1, 2, 3, 3])
b = np.unique([2, 3, 4, 4, 5, 6, 5])
np.in1d(a, b)

array([False,  True,  True])

In [166]:
 1 in a

True

In [167]:
 1 in b

False

In [168]:
np.all(np.in1d(a, b))

False

In [169]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [170]:
np.intersect1d(a, b)

array([2, 3])

In [171]:
 np.setdiff1d(a, b)

array([1])

In [172]:
np.setdiff1d(b, a)

array([4, 5, 6])

In [173]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [175]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

(1, 2, 3, 4, 5)

In [176]:
data.T.shape

(5, 4, 3, 2, 1)

In [177]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [179]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [180]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [181]:
A = np.arange(9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
x = np.arange(3)
x

array([0, 1, 2])

In [183]:
np.dot(A, x)

array([ 5, 14, 23])

In [184]:
A.dot(x)

array([ 5, 14, 23])

In [187]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

In [188]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [189]:
A = np.matrix(A)
B = np.matrix(B)
Ap = B * A * B.I

In [190]:
A = np.asmatrix(A)
B = np.asmatrix(B)
Ap = B * A * B.I
Ap = np.asarray(Ap)

In [191]:
np.inner(x, x)

5

In [192]:
np.dot(x, x)

5

In [193]:
y = x[:, np.newaxis]
y

array([[0],
       [1],
       [2]])

In [194]:
np.dot(y.T, y)

array([[5]])

In [195]:
x = np.array([1, 2, 3])
np.outer(x, x)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [196]:
np.kron(x, x)

array([1, 2, 3, 2, 4, 6, 3, 6, 9])

In [197]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [198]:
np.kron(np.ones((2,2)), np.identity(2))

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [199]:
np.kron(np.identity(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [200]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.einsum("n,n", x, y)

70

In [201]:
np.inner(x, y)

70

In [202]:
A = np.arange(9).reshape(3, 3)
B = A.T
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [204]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True